# Generated by Django 3.2.9 on 2022-03-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
