# Generated by Django 4.0.3 on 2022-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_profile_estatusflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_submit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
