# Generated by Django 4.0.3 on 2022-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profile_checked_profile_is_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ealimNotPass',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edhakhilwhichClass',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ealim',
            field=models.CharField(blank=True, choices=[('', '----'), ('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=20),
        ),
    ]
