# Generated by Django 4.0.3 on 2022-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_remove_profile_ealimnotpass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eCookingWomen',
            field=models.CharField(blank=True, max_length=314, null=True),
        ),
    ]
