# Generated by Django 4.0.3 on 2022-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_profile_ehighestdegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
