# Generated by Django 4.0.3 on 2022-06-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_profile_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='efigure',
        ),
    ]
