# Generated by Django 4.0.3 on 2022-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_remove_profile_efigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eforojporda',
            field=models.CharField(default='', max_length=300),
        ),
    ]
