# Generated by Django 4.0.3 on 2022-06-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_profile_eforojporda'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eKowmiMadrasaClass',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
