# Generated by Django 4.0.3 on 2022-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_profile_ekowmimadrasaclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eGrowUpAddress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eparmanentAddress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='epresentAddress',
            field=models.CharField(max_length=250),
        ),
    ]
