# Generated by Django 4.0.3 on 2022-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_profile_ediplomainstitute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='efazilSubject',
            field=models.CharField(blank=True, max_length=304, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='efaziluniversity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ekamilSubject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ekamilversity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
