# Generated by Django 4.0.3 on 2022-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_alter_profile_efazilsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eincome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eoccupation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eworkingPlace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
