# Generated by Django 4.0.3 on 2022-06-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_profile_esamiloyalty_alter_profile_efatheroccupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eclothMan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eclothWomen',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edari',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='euncle',
            field=models.CharField(blank=True, max_length=354, null=True),
        ),
    ]
