# Generated by Django 4.0.3 on 2022-06-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_alter_profile_esalat_alter_profile_esalatstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edhaknu',
            field=models.CharField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eislamicbook',
            field=models.CharField(max_length=354),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emazar',
            field=models.CharField(max_length=354),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emazhab',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emehnot',
            field=models.CharField(max_length=354),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emovie',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emurid',
            field=models.CharField(max_length=354),
        ),
        migrations.AlterField(
            model_name='profile',
            name='epolitics',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='equran',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='esalat',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='escholar',
            field=models.CharField(max_length=354),
        ),
    ]
