# Generated by Django 4.0.3 on 2022-06-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_alter_profile_eeducation_alter_profile_ejob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ebiyeSunnat',
            field=models.CharField(max_length=354),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edenmohar',
            field=models.CharField(max_length=354),
        ),
    ]
