# Generated by Django 4.0.3 on 2022-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_alter_profile_ebiyesunnat_alter_profile_edenmohar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eLPDistrict',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eLPEducationalQualification',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eLPHeight',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eLPMaritalStatus',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eLPSkinColor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eLPYear',
            field=models.CharField(max_length=150),
        ),
    ]
