# Generated by Django 4.0.3 on 2022-06-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0027_alter_profile_eguardiannumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_biodata',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
