# Generated by Django 4.0.3 on 2022-06-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_profile_update_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ehavingBrother',
            field=models.CharField(choices=[('', '----'), ('ভাই নেই', 'ভাই নেই'), ('১ জন', '১ জন'), ('২ জন', '২ জন'), ('৩ জন', '৩ জন'), ('৪ জন', '৪ জন'), ('৫ জন', '৫ জন'), ('৬ জন', '৬ জন'), ('৭ জন', '৭ জন'), ('৮ জন', '৮ জন'), ('৯ জন', '৯ জন'), ('১০ জন', '১০ জন'), ('১১ জন', '১১ জন'), ('১২ জন', '১২ জন'), ('১৩ জন', '১৩ জন'), ('১৪ জন', '১৪ জন'), ('১৪ জনের বেশি', '১৪ জনের বেশি')], default='----', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ehavingSister',
            field=models.CharField(choices=[('', '----'), ('বোন নেই', 'বোন নেই'), ('১ জন', '১ জন'), ('২ জন', '২ জন'), ('৩ জন', '৩ জন'), ('৪ জন', '৪ জন'), ('৫ জন', '৫ জন'), ('৬ জন', '৬ জন'), ('৭ জন', '৭ জন'), ('৮ জন', '৮ জন'), ('৯ জন', '৯ জন'), ('১০ জন', '১০ জন'), ('১১ জন', '১১ জন'), ('১২ জন', '১২ জন'), ('১৩ জন', '১৩ জন'), ('১৪ জন', '১৪ জন'), ('১৪ জনের বেশি', '১৪ জনের বেশি')], default='----', max_length=15),
        ),
    ]
