# Generated by Django 4.0.3 on 2022-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0029_alter_profile_ehavingbrother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
