# Generated by Django 4.0.3 on 2022-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0030_profile_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
    ]
