# Generated by Django 4.0.3 on 2022-08-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0031_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_user',
            old_name='user',
            new_name='userv',
        ),
    ]
