# Generated by Django 4.0.3 on 2022-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0036_alter_profile_userv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
