# Generated by Django 4.0.3 on 2022-08-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_remove_profile_userv_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_user',
            name='user',
        ),
    ]
