# Generated by Django 4.0.3 on 2022-08-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_remove_post_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
