# Generated by Django 4.0.3 on 2022-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0041_profile_userv_delete_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userv',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
