# Generated by Django 4.0.3 on 2022-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0042_alter_profile_userv'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='profile.ipmodel'),
        ),
    ]
