# Generated by Django 4.0.3 on 2022-10-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0043_ipmodel_remove_profile_userv_remove_profile_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upazila',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
    ]
