# Generated by Django 4.0.3 on 2022-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='enroled',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
