# Generated by Django 4.0.3 on 2022-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0047_alter_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
