# Generated by Django 4.0.3 on 2023-02-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_alter_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('All Levels', 'All Levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='All Levels', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('running', 'running'), ('closed', 'closed')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
