# Generated by Django 4.0.3 on 2023-02-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0053_remove_course_instructor_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=700)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='forWhome',
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.ManyToManyField(to='profile.audience'),
        ),
    ]
