# Generated by Django 4.0.3 on 2023-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0054_audience_remove_course_forwhome_course_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
