# Generated by Django 4.0.3 on 2023-02-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0056_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video',
            new_name='video',
        ),
    ]
