# Generated by Django 4.0.3 on 2023-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0057_rename_video_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
