# Generated by Django 4.1.7 on 2023-02-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0060_remove_course_video_content_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.content'),
        ),
    ]
