# Generated by Django 4.1.7 on 2023-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0064_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='duration',
            new_name='length',
        ),
    ]
