# Generated by Django 4.1.7 on 2023-02-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0066_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.IntegerField(),
        ),
    ]
