# Generated by Django 4.1.7 on 2023-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0068_remove_course_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='term',
            field=models.CharField(default='3h 20m', max_length=20),
        ),
    ]
