# Generated by Django 4.1.7 on 2023-02-28 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_cuser'),
        ('profile', '0069_video_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout'),
        ),
    ]
