# Generated by Django 4.1.7 on 2023-03-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0071_remove_course_course_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='shortDescription',
        ),
        migrations.RemoveField(
            model_name='course',
            name='whatLearn',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='https://us04web.zoom.us/j/79969674890?pwd=zpll6laDg59zwfwUSPbTYPZnIVfACS.1', max_length=400),
        ),
    ]
