# Generated by Django 4.1.7 on 2023-03-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0073_alter_content_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='checkout',
        ),
    ]
