# Generated by Django 4.1.7 on 2023-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('cnumber', models.CharField(max_length=100)),
                ('cBkashNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cBkashTransactionID', models.CharField(blank=True, max_length=200, null=True)),
                ('cRocketNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cRocketTransactionID', models.CharField(blank=True, max_length=200, null=True)),
                ('cNagadNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('cNagadTransactionID', models.CharField(blank=True, max_length=200, null=True)),
                ('estatus', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
