# Generated by Django 4.1.7 on 2023-03-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0074_remove_usercourse_checkout'),
        ('checkout', '0004_checkout_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='usercourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.usercourse'),
        ),
    ]
